spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/phpdb
    username: phpkosal
    password: kosall01
  jpa:
    properties:
      hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
        ddl-auto: update
  liquibase:
    change-log: classpath:db/changelog/db_changelog_master.yml
    enabled: true
    
  mvc:
     pathmatch:
          matching-strategy: ant_path_matcher
  
server:
  port: 8084




